apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-app-satr
spec:
  environments:
    - name: development
      build:
        from: main
    - name: prod
      build:
        from: release
  components:
    - name: server
      src: ./backend
      ports:
        - name: http
          port: 3000
      variables:
        PORT: 3000
      node:
        gpu: nvidia-v100,NviDia-p100,-nvidia-k80
    - name: server2
      src: ./backend
      ports:
        - name: http
          port: 3000
      node:
        gpu: nvidia-v100
        gpuCount: 4
    - name: server3
      src: ./backend
      ports:
        - name: http
          port: 3000
      node:
        gpu: nvidia-p100
        gpuCount: 6
      environmentConfig:
        - environment: prod
          variables:
            NODE_ENV: production
    - name: www
      src: ./frontend
      dockerfileName: Dockerfile
      ports:
        - name: http
          port: 3007
      publicPort: http
      variables:
        PORT: 3007
        ECHO_URL: "http://server:3000"
      environmentConfig:
        - environment: development
          replicas: 2
        - environment: prod
          horizontalScaling:
            minReplicas: 2
            maxReplicas: 5
          variables:
            NODE_ENV: production
    - name: www2
      src: ./frontend2
      dockerfileName: Dockerfile2
      ports:
        - name: http
          port: 3008
      publicPort: http
      variables:
        PORT: 3008
        ECHO_URL: "http://server:3000"
  dnsAppAlias:
    environment: prod
    component: www
