apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-app
spec:
  environments:
    - name: development
      build:
        from: main
    - name: prod
      build:
        from: release
  components:
    - name: server
      src: ./backend
      ports:
        - name: http
          port: 3000
      public: false
      environmentConfig:
        - environment: prod
          variables:
            PORT: 3000
            NODE_ENV: production
          monitoring: true
          resources:
            requests:
              memory: "43Mi"
              cpu: "10m"
            limits:
              memory: "43Mi"
              cpu: "10m"
          secrets:
            - DB_USER
            - DB_PASSWORD
        - environment: development
          variables:
            PORT: 3000
          monitoring: true
          resources:
            requests:
              memory: "41Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
              cpu: "10m"
          secrets:
            - DB_USER
            - DB_PASSWORD
    - name: www
      src: ./frontend
      ports:
        - name: http
          port: 3001
      publicPort: http
      environmentConfig:
        - environment: prod
          variables:
            PORT: 3001
            NODE_ENV: production
            ECHO_URL: "http://server:3000"
          monitoring: false
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
              cpu: "10m"
          horizontalScaling:
            minReplicas: 2
            maxReplicas: 4
        - environment: development
          replicas: 2
          variables:
            PORT: 3001
            NODE_ENV: production
            ECHO_URL: "http://server:3000"
          monitoring: false
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
              cpu: "20m"
  dnsAppAlias:
    environment: development
    component: www
  dnsExternalAlias:
    - alias: radix-app.equinor.com
      environment: prod
      component: www
    - alias: radix-app-alt.equinor.com
      environment: prod
      component: www